# Generated by Django 5.0 on 2023-12-08 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories_Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('total_produits', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Categories_Produit',
                'verbose_name_plural': 'Categories_Produits',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_et_prenom', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=50)),
                ('autre_information', models.TextField()),
            ],
            options={
                'verbose_name': 'grossiste',
                'verbose_name_plural': 'grossistes',
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_et_prenom', models.CharField(max_length=150)),
                ('nom_societe', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('autre_information', models.TextField()),
            ],
            options={
                'verbose_name': 'fournisseur',
                'verbose_name_plural': 'fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='Grossiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_et_prenom', models.CharField(max_length=150)),
                ('nom_societe', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('autre_information', models.TextField()),
            ],
            options={
                'verbose_name': 'grossiste',
                'verbose_name_plural': 'grossistes',
            },
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('prix_en_gros', models.FloatField()),
                ('prix_details', models.FloatField()),
                ('prix_fournisseur', models.FloatField()),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock_app.categories_produit')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='Entrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_total', models.FloatField()),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock_app.fournisseur')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock_app.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Sortie_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_total', models.FloatField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock_app.client')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock_app.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Sortie_grossiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_total', models.FloatField()),
                ('grossiste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock_app.grossiste')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock_app.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_produit', models.IntegerField()),
                ('total_produit_restants', models.IntegerField()),
                ('total_produit_sortis', models.IntegerField(default=0)),
                ('total_produit_entrant', models.IntegerField(default=0)),
                ('seuil_alerte_produit', models.IntegerField(default=5)),
                ('alerte', models.BooleanField(default=False)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock_app.produit')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
    ]
