# Generated by Django 5.0 on 2023-12-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories_produit',
            options={'verbose_name': 'Categorie de Produit', 'verbose_name_plural': 'Categories de  Produits'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='sortie_client',
            options={'verbose_name': 'Sortie de client', 'verbose_name_plural': 'Sortie de clients'},
        ),
        migrations.AlterModelOptions(
            name='sortie_grossiste',
            options={'verbose_name': 'Sortie de grossiste', 'verbose_name_plural': 'Sortie de grossistes'},
        ),
        migrations.AlterField(
            model_name='categories_produit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='categories_produit',
            name='total_produits',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='autre_information',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entrer',
            name='prix_total',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='autre_information',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='nom_et_prenom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='nom_societe',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='grossiste',
            name='autre_information',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='grossiste',
            name='nom_societe',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sortie_client',
            name='prix_total',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sortie_grossiste',
            name='prix_total',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='alerte',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='seuil_alerte_produit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total_produit_entrant',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total_produit_restants',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total_produit_sortis',
            field=models.IntegerField(blank=True),
        ),
    ]
