# Generated by Django 5.0 on 2023-12-19 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock_app', '0002_alter_categories_produit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='produit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_stock_app.produit'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='seuil_alerte_produit',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total_produit',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total_produit_entrant',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total_produit_restants',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total_produit_sortis',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
