# Generated by Django 5.0 on 2023-12-24 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock_app', '0003_alter_stock_produit_alter_stock_seuil_alerte_produit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intituler', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AlertHistorique',
                'verbose_name_plural': 'AlertHistoriques',
            },
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['nom_produit'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterField(
            model_name='entrer',
            name='quantite',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_details',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(1000000000000000000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_en_gros',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(1000000000000000000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_fournisseur',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(1000000000000000000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='sortie_client',
            name='quantite',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='sortie_grossiste',
            name='quantite',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='stock',
            name='seuil_alerte_produit',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total_produit',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
