# Generated by Django 5.0 on 2023-12-26 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock_app', '0004_alerthistorique_alter_produit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='total_produit_restants',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
