# Generated by Django 5.0 on 2023-12-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock_app', '0005_alter_stock_total_produit_restants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerthistorique',
            options={'ordering': ['-date'], 'verbose_name': 'AlertHistorique', 'verbose_name_plural': 'AlertHistoriques'},
        ),
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alerthistorique',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
