# Generated by Django 5.0 on 2023-12-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock_app', '0006_alter_alerthistorique_options_stock_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerthistorique',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
