# Generated by Django 5.0 on 2023-12-29 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stock_app', '0007_alter_alerthistorique_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortie_client',
            name='nom_prenom_client',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='sortie_client',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_stock_app.client'),
        ),
    ]
